### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by IzzySoft** [by-syk/NetUpDown#1]
Unfortunately, the Playstore link just leads to a 404 error page – seems the app wasn't published yet. Would you mind attaching the `.apk` file to the `releases/` page, with the corresponding release, so one could easily grab it from there? That would, in addition, also help those without Playstore access.

Thanks!

**Comment by by-syk** [comment]
Sorry, I'm preparing to release to Play. Now I've attached the APK to the `releases` page.

**Comment by IzzySoft** [comment]
Thanks! I'll fetch that ASAP and include it with [my F-Droid compatible repo](https://android.izzysoft.de/repo) then. Should be listed within a few hours, and get auto-updated within 24h whenever you tag a new release and attach the `.apk` to it. I'll update this issue with a link when done, so you can point other users there if you like.

**Comment by IzzySoft** [comment]
Congrats, it's now listed at Play! And as well [at my repo](https://apt.izzysoft.de/fdroid/index/apk/com.by_syk.netupdown), so folks without Playstore access can get it using the F-Droid client. So thanks again for adding the `.apk`, and big success for your app!

PS: May I suggest to use an English name for `application: label=` with the next version? ;)
- Currently: `application: label='上行速' icon='res/mipmap-mdpi-v4/ic_launcher.png'`
- Suggested: `application: label='Upstream' icon='res/mipmap-mdpi-v4/ic_launcher.png'`

There's still `application-label-zh:'上行速'` for the localized name :)

**Comment by by-syk** [comment]
@lzzySoft Thank you very much. There are two language resources, English and Chinese yet. You could see them in `/res/values/strings.xml` and `res/values-zh/strings.xml`. So the `application:label` has also two values: `Upstream` for default and `上行速` for Chinese.

**Comment by IzzySoft** [comment]
There's only one default (i.e. without a "locale addon"), and that's what fdroidserver picks. Usually, one puts the English name there (to my experience). You've put the ZH variant in both places, the English one is only mentioned in "launchable activity" (i.e. the name of the main activity, not the name of the app):

```
application-label-zh:'上行速'
application: label='上行速' icon='res/mipmap-mdpi-v4/ic_launcher.png'
launchable-activity: name='com.by_syk.netupdown.PrefActivityHoneycomb'  label='Upstream' icon=''
```

Here the second line should better read like

```
application: label='Upstream' icon='res/mipmap-mdpi-v4/ic_launcher.png'
```

Otherwise, most people outside China cannot read the name. Just a suggestion :)

Oh, if you allow me a second suggestion: What license is used for your app? There's no information in your project here. Might be a good idea to add one :)

**Comment by by-syk** [comment]
@lzzySoft Maybe you are using `aapt` to get these. I tried to use `aapt` and found that the value of `application: label` is in Chinese. I don't know why but I'm sure that the default language is English.

I got your suggestion and added the **Apache License**.

Thank you.

**Comment by IzzySoft** [comment]
Indeed to my knowledge that's what fdroidserver uses to obtain those metadata – as pointed above. I've checked its code, and it works as explained, picking the app name from that `application: label=` line. That why I suggested changing that one.

Thanks for adding the license, will update Metadata here ASAP.
