### ISSUE TITLE
Would you support a F-Droid store inclusion?

### ISSUE THREAD

**Issue by revuwa** [by-syk/NetUpDown#4]
Thanks for your nice app, and for publishing the source code.

It would be great to see your app in the [F-Droid](https://f-droid.org/) store and made an request for packaging, already [here](https://gitlab.com/fdroid/rfp/issues/460).
Would this be OK for you and would you support the inclusion?

**Comment by by-syk** [comment]
ok

**Comment by hotlittlewhitedog** [comment]
I'm coming from F-Droid (above link). 
Maybe you should create a widget 😃

**Comment by by-syk** [comment]
Widget?

**Comment by hotlittlewhitedog** [comment]
Small app (not full app activity) on the home. Like killerapp with a status.

**Comment by by-syk** [comment]
No. It's useless for the app.
